### PR TITLE
map store-id to group-id

### PR DESCRIPTION
**Pull request by james97**

### CODE REVIEW

**Comment by SiweiYang** [comment]
Something wrong, please check.

**Comment by SiweiYang** [comment]
Something wrong, please check.

**Comment by SiweiYang** [comment]
Something wrong, please check.

**Comment by SiweiYang** [comment]
This build passes all tests. Good job!

**Comment by james97** [comment]
build

**Comment by SiweiYang** [comment]
This build passes all tests. Good job!

**Comment by james97** [comment]
build

**Comment by SiweiYang** [comment]
This build passes all tests. Good job!

**Pull request merged**
