### PR TITLE
exclude irrelevant target users if target users is biased

### PR DESCRIPTION
**Pull request by james97**
also add en/fr query map to use HLC info from other language

### CODE REVIEW

**Comment by james97** [comment]
build

**Comment by SiweiYang** [comment]
Something wrong, please check.

**Comment by james97** [comment]
build

**Comment by SiweiYang** [comment]
Something wrong, please check.

**Comment by james97** [comment]
build

**Comment by SiweiYang** [comment]
Something wrong, please check.

**Comment by SiweiYang** [comment]
Something wrong, please check.

**Comment by james97** [comment]
build

**Comment by SiweiYang** [comment]
Something wrong, please check.

**Comment by james97** [comment]
build

**Comment by SiweiYang** [comment]
Something wrong, please check.

**Comment by SiweiYang** [comment]
Something wrong, please check.

**Comment by james97** [comment]
build

**Comment by SiweiYang** [comment]
Something wrong, please check.

**Comment by james97** [comment]
build

**Comment by SiweiYang** [comment]
This build passes all tests. Good job!

**Comment by james97** [comment]
build

**Comment by SiweiYang** [comment]
This build passes all tests. Good job!

**Pull request merged**
